"""add locations, nvr_devices, and camera_actions tables

Revision ID: b68537833ed5
Revises: d7a9a1232c36
Create Date: 2025-11-20 11:58:42.448404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b68537833ed5'
down_revision: Union[str, Sequence[str], None] = 'd7a9a1232c36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=False),
    sa.Column('location_type', sa.String(), nullable=True),
    sa.Column('item_location', sa.String(), nullable=True),
    sa.Column('old_location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_name')
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_table('nvr_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nvr_name', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('channel_number', sa.String(), nullable=True),
    sa.Column('switch_port', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nvr_name')
    )
    op.create_index(op.f('ix_nvr_devices_id'), 'nvr_devices', ['id'], unique=False)
    op.create_table('camera_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('action_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_actions_id'), 'camera_actions', ['id'], unique=False)
    op.add_column('cameras', sa.Column('location_id', sa.Integer(), nullable=True))
    op.add_column('cameras', sa.Column('nvr_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cameras', 'locations', ['location_id'], ['id'])
    op.create_foreign_key(None, 'cameras', 'nvr_devices', ['nvr_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cameras', type_='foreignkey')
    op.drop_constraint(None, 'cameras', type_='foreignkey')
    op.drop_column('cameras', 'nvr_id')
    op.drop_column('cameras', 'location_id')
    op.drop_index(op.f('ix_camera_actions_id'), table_name='camera_actions')
    op.drop_table('camera_actions')
    op.drop_index(op.f('ix_nvr_devices_id'), table_name='nvr_devices')
    op.drop_table('nvr_devices')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
