"""create cameras table

Revision ID: d7a9a1232c36
Revises: 
Create Date: 2025-11-20 10:41:57.164814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7a9a1232c36'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_no', sa.String(), nullable=False),
    sa.Column('item_description', sa.String(), nullable=True),
    sa.Column('model_no', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('rta_tag', sa.String(), nullable=True),
    sa.Column('camera_name', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('mac_address', sa.String(), nullable=True),
    sa.Column('firmware_version', sa.String(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('sd_card', sa.Boolean(), nullable=True),
    sa.Column('sd_capacity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('camera_status', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('is_asset', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address'),
    sa.UniqueConstraint('mac_address')
    )
    op.create_index(op.f('ix_cameras_id'), 'cameras', ['id'], unique=False)
    op.create_index(op.f('ix_cameras_serial_no'), 'cameras', ['serial_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cameras_serial_no'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_id'), table_name='cameras')
    op.drop_table('cameras')
    # ### end Alembic commands ###
